name: Python Tests with Report

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-interaction --no-ansi

    - name: Run tests with HTML report
      run: |
        poetry run pytest --html=report.html --self-contained-html

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: report.html
